### ISSUE TITLE
SMTCAdapter.dll source code

### ISSUE THREAD

**Issue by toasterofbread** [Selemba1000/JavaMediaTransportControls#1]
I'd like to use this library in my project, but the lack of (unless I'm missing it) source code for the SMTCAdapter.dll files is giving me pause. 

Would you be able to make it available, or point me to the source, so that I can compile them myself? Thanks.

**Comment by Selemba1000** [comment]
Give me another week or so. I still need to do some cleanup and scripting. But source will be coming.

**Comment by Selemba1000** [comment]
Source is published in commit 73d55ee. I hope this helps.

**Comment by toasterofbread** [comment]
Thanks!

**Comment by Selemba1000** [comment]
The library is now available via Maven Central if you want to include it in your project more easily.

**Comment by sayaka-sh** [comment]
I used the C++ code from this project as part of the Windows implementation in my [Kotlin library](https://github.com/toasterofbread/mediasession-kt). Thanks again!
